"""
Root Bazel module configuration file that defines dependencies and external repositories.
"""

module(
    name = "nod",
    version = "0.1.0",
)

bazel_dep(name = "aspect_rules_py", version = "1.11.7")
bazel_dep(name = "bazel_lib", version = "3.7.1")
bazel_dep(name = "bazel_skylib", version = "1.9.2")
bazel_dep(name = "bazel_utils_bazel", version = "0.1.1")
bazel_dep(name = "bazel_utils_buf", version = "0.1.1")
bazel_dep(name = "bazel_utils_core", version = "0.1.1")
bazel_dep(name = "bazel_utils_go", version = "0.1.1")
bazel_dep(name = "bazel_utils_md", version = "0.1.1")
bazel_dep(name = "bazel_utils_python", version = "0.1.1")
bazel_dep(name = "bazel_utils_rust", version = "0.1.1")
bazel_dep(name = "gazelle", version = "0.52.2")
bazel_dep(name = "platforms", version = "1.1.0")
bazel_dep(name = "protobuf", version = "35.1")
bazel_dep(name = "rules_go", version = "0.62.0")
bazel_dep(name = "rules_python", version = "2.3.0")
bazel_dep(name = "rules_rust", version = "0.73.0")
bazel_dep(name = "rules_shell", version = "0.8.0")
bazel_dep(name = "toolchains_llvm", version = "1.8.0")

include("//:buf.MODULE.bazel")
include("//:go.MODULE.bazel")
include("//:python.MODULE.bazel")
include("//:rust.MODULE.bazel")
include("//third_party/buf/plugins/protoc-gen-protovalidate-buffa:crates.MODULE.bazel")

git_override(
    module_name = "bazel_utils_bazel",
    remote = "https://github.com/amsokol/bazel_utils.git",
    strip_prefix = "bazel",
    tag = "v0.1.1",
)

git_override(
    module_name = "bazel_utils_buf",
    remote = "https://github.com/amsokol/bazel_utils.git",
    strip_prefix = "buf",
    tag = "v0.1.1",
)

git_override(
    module_name = "bazel_utils_core",
    remote = "https://github.com/amsokol/bazel_utils.git",
    strip_prefix = "core",
    tag = "v0.1.1",
)

git_override(
    module_name = "bazel_utils_go",
    remote = "https://github.com/amsokol/bazel_utils.git",
    strip_prefix = "go",
    tag = "v0.1.1",
)

git_override(
    module_name = "bazel_utils_md",
    remote = "https://github.com/amsokol/bazel_utils.git",
    strip_prefix = "markdown",
    tag = "v0.1.1",
)

git_override(
    module_name = "bazel_utils_python",
    remote = "https://github.com/amsokol/bazel_utils.git",
    strip_prefix = "python",
    tag = "v0.1.1",
)

git_override(
    module_name = "bazel_utils_rust",
    remote = "https://github.com/amsokol/bazel_utils.git",
    strip_prefix = "rust",
    tag = "v0.1.1",
)
