# Generated from api/v1/echo.proto. DO NOT EDIT.
# Generated by protoc-gen-connectrpc-py v0.11.1 with parameter "".
# ruff: noqa: PGH004
# ruff: noqa
# fmt: off

from __future__ import annotations

from typing import Protocol, TYPE_CHECKING

from connectrpc.client import ConnectClient, ConnectClientSync
from connectrpc.code import Code
from connectrpc.errors import ConnectError
from connectrpc.method import IdempotencyLevel, MethodInfo
from connectrpc.server import ConnectASGIApplication, ConnectWSGIApplication, Endpoint, EndpointSync

from .echo_pb import EchoRequest, EchoResponse

if TYPE_CHECKING:
    from collections.abc import AsyncGenerator, Iterable, Mapping

    from connectrpc.codec import Codec
    from connectrpc.compression import Compression
    from connectrpc.interceptor import Interceptor, InterceptorSync
    from connectrpc.request import Headers, RequestContext


class EchoService(Protocol):
    async def echo(self, request: EchoRequest, ctx: RequestContext[EchoRequest, EchoResponse]) -> EchoResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')


class EchoServiceASGIApplication(ConnectASGIApplication[EchoService]):
    def __init__(
        self,
        service: EchoService | AsyncGenerator[EchoService],
        *,
        interceptors: Iterable[Interceptor] = (),
        read_max_bytes: int | None = None,
        compressions: Iterable[Compression] | None = None,
        codecs: Iterable[Codec] | None = None,
    ) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/api.v1.EchoService/Echo": Endpoint.unary(
                    method=MethodInfo(
                        name="Echo",
                        service_name="api.v1.EchoService",
                        input=EchoRequest,
                        output=EchoResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.echo,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/api.v1.EchoService"


class EchoServiceClient(ConnectClient):
    async def echo(
        self,
        request: EchoRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> EchoResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="Echo",
                service_name="api.v1.EchoService",
                input=EchoRequest,
                output=EchoResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

class EchoServiceSync(Protocol):
    def echo(self, request: EchoRequest, ctx: RequestContext[EchoRequest, EchoResponse]) -> EchoResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')


class EchoServiceWSGIApplication(ConnectWSGIApplication):
    def __init__(
        self,
        service: EchoServiceSync,
        interceptors: Iterable[InterceptorSync] = (),
        read_max_bytes: int | None = None,
        compressions: Iterable[Compression] | None = None,
        codecs: Iterable[Codec] | None = None,
    ) -> None:
        super().__init__(
            endpoints={
                "/api.v1.EchoService/Echo": EndpointSync.unary(
                    method=MethodInfo(
                        name="Echo",
                        service_name="api.v1.EchoService",
                        input=EchoRequest,
                        output=EchoResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.echo,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/api.v1.EchoService"


class EchoServiceClientSync(ConnectClientSync):
    def echo(
        self,
        request: EchoRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> EchoResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="Echo",
                service_name="api.v1.EchoService",
                input=EchoRequest,
                output=EchoResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
