// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: api/v1/echo.proto

package apiv1

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// EchoServiceName is the fully-qualified name of the EchoService service.
	EchoServiceName = "api.v1.EchoService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// EchoServiceEchoProcedure is the fully-qualified name of the EchoService's Echo RPC.
	EchoServiceEchoProcedure = "/api.v1.EchoService/Echo"
)

// EchoServiceClient is a client for the api.v1.EchoService service.
type EchoServiceClient interface {
	// Echo returns the same message that was sent.
	Echo(context.Context, *EchoRequest) (*EchoResponse, error)
}

// NewEchoServiceClient constructs a client for the api.v1.EchoService service. By default, it uses
// the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewEchoServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) EchoServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	echoServiceMethods := File_api_v1_echo_proto.Services().ByName("EchoService").Methods()
	return &echoServiceClient{
		echo: connect.NewClient[EchoRequest, EchoResponse](
			httpClient,
			baseURL+EchoServiceEchoProcedure,
			connect.WithSchema(echoServiceMethods.ByName("Echo")),
			connect.WithClientOptions(opts...),
		),
	}
}

// echoServiceClient implements EchoServiceClient.
type echoServiceClient struct {
	echo *connect.Client[EchoRequest, EchoResponse]
}

// Echo calls api.v1.EchoService.Echo.
func (c *echoServiceClient) Echo(ctx context.Context, req *EchoRequest) (*EchoResponse, error) {
	response, err := c.echo.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// EchoServiceHandler is an implementation of the api.v1.EchoService service.
type EchoServiceHandler interface {
	// Echo returns the same message that was sent.
	Echo(context.Context, *EchoRequest) (*EchoResponse, error)
}

// NewEchoServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewEchoServiceHandler(svc EchoServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	echoServiceMethods := File_api_v1_echo_proto.Services().ByName("EchoService").Methods()
	echoServiceEchoHandler := connect.NewUnaryHandlerSimple(
		EchoServiceEchoProcedure,
		svc.Echo,
		connect.WithSchema(echoServiceMethods.ByName("Echo")),
		connect.WithHandlerOptions(opts...),
	)
	return "/api.v1.EchoService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case EchoServiceEchoProcedure:
			echoServiceEchoHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedEchoServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedEchoServiceHandler struct{}

func (UnimplementedEchoServiceHandler) Echo(context.Context, *EchoRequest) (*EchoResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.v1.EchoService.Echo is not implemented"))
}
