load("@bazel_skylib//rules:native_binary.bzl", "native_test")

native_test(
    name = "lint",
    size = "small",
    src = "//bazel/lint:golangci-lint",
    out = "lint",
    args = [
        "run",
        "./go/...",
    ],
    data = [
        "//:.golangci.yaml",
        "//:go.mod",
        "//:go.sum",
        "//go/api:lint_srcs",
        "//go/echo/cmd/client:lint_srcs",
        "//go/echo/cmd/server:lint_srcs",
    ],
    # go list needs modules; sandbox has GOPROXY=off and no cache.
    local = True,
)
