load("//bazel/lint:golangci.bzl", "golangci_test")

golangci_test(
    name = "lint",
    size = "small",
    flags = [
        "run",
        "./go/...",
    ],
    # go list needs modules; sandbox has GOPROXY=off and no cache.
    local = True,
    tags = [
        "external",
        "no-cache",
        "no-sandbox",
    ],
)
