//! Checked-in Protobuf / Connect stubs for `api.v1`.
//!
//! Generated by `buf generate --template buf.gen.rust.yaml` into `gen/`
//! (`file_per_package` — one `<pkg>.rs` per tree, no packaging plugin).
//!
//! Call sites use `api::v1::{...}` (crate name + proto version). Internal
//! `buffa` / `connect` trees keep the proto package path for
//! `buffa_module=crate::buffa`.

#![allow(clippy::all)]
#![allow(dead_code, unused_imports, unused_qualifications)]

/// Buffa-generated message types (`crate::buffa::api::v1`).
pub mod buffa {
    pub mod api {
        pub mod v1 {
            include!("../gen/buffa/api.v1.rs");
        }
    }
}

/// Connect-generated service stubs (`crate::connect::api::v1`).
pub mod connect {
    pub mod api {
        pub mod v1 {
            include!("../gen/connect/api.v1.rs");
        }
    }
}

/// Unified facade: messages + service stubs as `api::v1`.
pub mod v1 {
    pub use crate::buffa::api::v1::*;
    pub use crate::connect::api::v1::*;
}
