load("@rules_rust//rust:defs.bzl", "rust_library")

exports_files(["Cargo.toml"])

rust_library(
    name = "api",
    srcs = glob([
        "src/**/*.rs",
        "gen/**/*.rs",
    ]),
    visibility = ["//visibility:public"],
    deps = [
        "@cargo//:buffa",
        "@cargo//:connectrpc",
        "@cargo//:protovalidate-buffa",
        "@cargo//:serde",
    ],
)
